server:
  port: 8080

logging:
  level:
    root: "INFO"
    com.slm.proguard: "INFO"
  file:
    path: "/tmp/proguard-example.log"
  pattern:
    console: "%d{ISO8601} [%-5level] [%-10thread] [%-30logger{2}] - %m%n"
    file: "%d{ISO8601} [%-5level] [%-10thread] [%-30logger{2}] - %m%n"

spring:
  application:
    name: "proguard-example"
    agent:
      javaagent: "C:\Users\idaoud\OneDrive - Deloitte (O365D)\Desktop\CCCC\applicationinsights-agent-3.4.19.jar"

